## Практическое задание

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
  

Количество столбцов в 1-й матрице должно совпадать с количеством строк во 2-й

Произведения не определены

 б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
  

А*B - Произведение определено, размерность матрицы будет 2х3

B*A - Произведениe не определенo

 в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
  

А*B - Произведение определено, размерность матрицы будет 8х8

B*А - Произведение определено, размерность матрицы будет 3х3

 г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

А*B - Произведение определено, размерность матрицы будет 4x4

B*А - Произведение определено, размерность матрицы будет 4x4

    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [39]:
import numpy as np

In [40]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


In [41]:
print(f'Матрица С = A * B\n{np.dot(a, b)}')

Матрица С = A * B
[[  4 -11]
 [ 12  -3]]


In [42]:
print(f'Матрица С = B * A \n{np.dot(b, a)}')

Матрица С = B * A 
[[ 1 -8]
 [15  0]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

In [43]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Матрица C\n{C}\n')
print(f'Матрица 3A − 2B + 4C = \n{3*A - 2*B + 4*C}')

Матрица A
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица C
[[ 2 -4]
 [ 1  1]]

Матрица 3A − 2B + 4C = 
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [44]:
A = np.array([[4, 1], [5, -2], [2, 3]])
At = A.T
print(f'Матрица:\n{A}\n')
print(f'Транспонированная матрица:\n{At}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]


In [45]:
print(f'𝐴𝐴𝑇:\n\n{np.dot(A, At)}\n')
print(f'𝐴𝑇𝐴:\n\n{np.dot(At, A)}')

𝐴𝐴𝑇:

[[17 18 11]
 [18 29  4]
 [11  4 13]]

𝐴𝑇𝐴:

[[45  0]
 [ 0 14]]



__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [46]:
A =[[1,7], [3,1]]
B =[[4,2], [5,8]]
def multi_two_matr (A,B):
    result =[[0 for x in range(len(A))] for y in range(len(B[0]))]
    assert len(A[0])==len(B)
    for i in range (len(A)):
        for j in range (len(B[0])):
            for k in range (len(A[0])):
                result[i][j] += A[i][k] *B[k][j]
    return result
print(multi_two_matr(A,B))

[[39, 58], [17, 14]]


## Практическое задание

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$



In [47]:
import math

In [48]:
x=0
a = np.array([[math.sin(x), (-1)*math.cos(x)], [math.cos(x), math.sin(x)]])
print(f'Матрица:\n{a}')
print(f'Определитель:\t{np.linalg.det(a):.0f}')

Матрица:
[[ 0. -1.]
 [ 1.  0.]]
Определитель:	1


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    


In [49]:
a = np.array([[4,2,3], [0,5,1], [0,0,9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\t{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:	180


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [50]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\t{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:	-0




__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
  

$det(A^{2})$ = $det(A) * det(A)$ = 4 * 4 = 16

 б) $det(A^{T})$;
    


$det(A^{T})$ = $det(A)$ = 4 

   в) $det(2A)$.

$det(2A)$ = $det(A)*2^n$ = $4*2^n$ (n - число строк в матрице А)



   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



Вы́рожденная ма́трица (синонимы: сингуля́рная ма́трица, осо́бая ма́трица, осо́бенная ма́трица) — квадратная матрица, определитель которой равен нулю. 

In [51]:
a = np.array([[-2,7,-3], [4,-14,6], [-3,7,13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\t{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:	0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [52]:
a = np.array([[1,2,3], [1,1,1], [2,3,4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы a):\t {r}')

Ранг матрицы a):	 2


In [53]:
a = np.array([[2,3,5,6], [0,0,2,2], [0,0,4,3],[0,0,2,1] ])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы б):\t {r}')

Ранг матрицы б):	 3
