### Задача 1
 
Контрольная работа состоит из пяти вопросов. На каждый вопрос приведено четыре варианта ответа, один из которых правильный. Составьте закон распределения числа правильных ответов при простом угадывании. Найдите M(X), D(X).


In [142]:
import numpy as np

Рассмотрим случайную величину, равную числу угадываниия правильных ответов

In [143]:
np.random.binomial(n=5, p=0.25)

2

Повторим этот эксперимент 20 раз и посмотрим, какие получаются значения

In [144]:
np.random.binomial(n=5, p=0.25, size=20)

array([0, 0, 1, 3, 1, 2, 2, 0, 2, 4, 1, 1, 2, 5, 1, 1, 2, 1, 3, 2])

 __Биномиальный закон__ описывает распределение случайной величины $X$, задающей число наступлений события $A$ в ходе проведения $n$ независимых опытов. Биномиальный закон распределения описывается __формулой Бернулли__:

$$P(X = k) = C_n^k p^k (1 - p)^{n - k}$$


Принимаемые значения данной случайной величины будут: $x_1 = 0$, $x_2 = 1$, $x_3 = 2$, $x_4 = 3$, $x_5 = 4$, $x_6 = 5$.

Посчитаем вероятность того, что $X = 0$, т.е. что из пяти вопросов нет ни одного правильнoго ответа:

$$P(X = 0) = C_n^k p^k (1 - p)^{n - k} = C_5^0 \cdot 0.25^0 \cdot 0.75^5 = \frac{5!}{0! \: (5-0)!} \cdot 0.25^0 \cdot 0.75^5 = 1 \cdot 1 \cdot 0.2373046875 = 0.2373046875.$$


Посчитаем вероятность каждого значения:

In [145]:
x = [0, 1, 2, 3, 4, 5]
k = [0, 1, 2, 3, 4, 5] 
n = 5

In [146]:
p = 0.25
q = 0.75

In [147]:
p0 = (np.math.factorial(n)/(np.math.factorial(x[0])*np.math.factorial(n-x[0])))*(p**k[0])*(q**(n-k[0]))
p1 = (np.math.factorial(n)/(np.math.factorial(x[1])*np.math.factorial(n-x[1])))*(p**k[1])*(q**(n-k[1]))
p2 = (np.math.factorial(n)/(np.math.factorial(x[2])*np.math.factorial(n-x[2])))*(p**k[2])*(q**(n-k[2]))
p3 = (np.math.factorial(n)/(np.math.factorial(x[3])*np.math.factorial(n-x[3])))*(p**k[3])*(q**(n-k[3]))
p4 = (np.math.factorial(n)/(np.math.factorial(x[4])*np.math.factorial(n-x[4])))*(p**k[4])*(q**(n-k[4]))
p5 = (np.math.factorial(n)/(np.math.factorial(x[5])*np.math.factorial(n-x[5])))*(p**k[5])*(q**(n-k[5]))

In [148]:
print(f'P(X = 0) = {(np.math.factorial(n)/(np.math.factorial(x[0])*np.math.factorial(n-x[0])))*(p**k[0])*(q**(n-k[0]))}')
print(f'P(X = 1) = {(np.math.factorial(n)/(np.math.factorial(x[1])*np.math.factorial(n-x[1])))*(p**k[1])*(q**(n-k[1]))}')
print(f'P(X = 2) = {(np.math.factorial(n)/(np.math.factorial(x[2])*np.math.factorial(n-x[2])))*(p**k[2])*(q**(n-k[2]))}')
print(f'P(X = 3) = {(np.math.factorial(n)/(np.math.factorial(x[3])*np.math.factorial(n-x[3])))*(p**k[3])*(q**(n-k[3]))}')
print(f'P(X = 4) = {(np.math.factorial(n)/(np.math.factorial(x[4])*np.math.factorial(n-x[4])))*(p**k[4])*(q**(n-k[4]))}')
print(f'P(X = 5) = {(np.math.factorial(n)/(np.math.factorial(x[5])*np.math.factorial(n-x[5])))*(p**k[5])*(q**(n-k[5]))}')
print(f'P = {p0+p1+p2+p3+p4+p5}')

P(X = 0) = 0.2373046875
P(X = 1) = 0.3955078125
P(X = 2) = 0.263671875
P(X = 3) = 0.087890625
P(X = 4) = 0.0146484375
P(X = 5) = 0.0009765625
P = 1.0


Закон распределения числа правильных ответов при простом угадывании:

<table border="3">
    <tr>
        <th>$x$</th>
        <td>0</td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
    </tr>
    <tr>
        <th>$P(X = x)$</th>
        <td>0.2373046875</td>
        <td>0.3955078125</td>
        <td>0.263671875</td>
        <td>0.087890625</td>
        <td>0.0146484375</td>
        <td>0.0009765625</td>
    </tr>
</table>

In [149]:
x_probabilities = np.array([0.2373046875, 0.3955078125, 0.263671875, 
                            0.087890625, 0.0146484375, 0.0009765625])
x_values = np.array([0, 1, 2, 3, 4, 5])

__Математическое ожидание__ для биномиально распределенной дискретной величины можно вычислить по формуле: 

$$M(X) = np$$



In [150]:
m = x_values.dot(x_probabilities)
print (f'Математическое ожидание: {m}')

Математическое ожидание: 1.25


__Дисперсия__ является мерой разброса случайной величины относительно ее среднего значения. Дисперсия для биномиально распределенной дискретной величины вычисляется так: 

$$D(X) = np(1-p)$$

__Дисперсией__ случайной величины $X$ называется математическое ожидание квадрата отклонения случайной величины от ее математического ожидания:
$$D(X) = M \left( (X - M(X))^2 \right).$$

Oпределим случайную величину $Y = X - M(X)$. Она будет принимать значения:

In [151]:
y_values = x_values - m
print(y_values)

[-1.25 -0.25  0.75  1.75  2.75  3.75]


Bозведем эту величину в квадрат, тем самым, получим новую случайную величину $Z$ со все еще таким же распределением вероятностей:

In [152]:
z_values = y_values ** 2

print(z_values)

[ 1.5625  0.0625  0.5625  3.0625  7.5625 14.0625]


In [153]:
print (f'Дисперсия случайной величины X равна: {np.math.sqrt(z_values.dot(x_probabilities))}')

Дисперсия случайной величины X равна: 0.9682458365518543


### Задача 2
 
Вероятность попадания в цель при одном выстреле равна 0.01. Какова вероятность того, что число попаданий при 200 выстрелах будет не менее 5 и не более 10?


$$P(X = k) = \dfrac{a^k e ^{-a}}{k!}.$$
Поскольку мы имеем дело со счётчиком (число попаданий), мы можем допустить, что рассматриваемая случайная величина имеет распределение Пуассона. Чтобы найти её параметр $a$, вспомним, что чем выше число экспериментов, тем больше биномиальное распределение "похоже" на распределение Пуассона с параметром $a = np$. В нашем случае $a = 200 \cdot 0.01 = 2$. Итак,

$$P(X = 5) = \dfrac{2^{5} \cdot e^{-2}}{5!} \approx 0.03608940886309672.$$

In [154]:
a = 2
k = 5

(a ** k) * (np.exp(-a)) / np.math.factorial(k)

0.03608940886309672

Для решения нужно сложить несколько вероятностей. Вероятность получить не менее 5 и не более 10 предполагает получение от 5 до 10 попаданий:
$$P(5 \leq X \leq 10) = \displaystyle\sum_{i = 5}^{10} \dfrac{2^{i} e^{-2}}{i!}$$


In [155]:
def poisson_proba(k, lambda_):
    
    return (lambda_ ** k) * (np.exp(-lambda_)) / np.math.factorial(k)

In [156]:
lambda_ = a

In [157]:
hits = [5,6,7,8,9,10]

Bероятность того, что число попаданий при 200 выстрелах будет не менее 5 и не более 10:

In [158]:
sum(poisson_proba(k=i, lambda_=lambda_) for i in hits)

0.052644709119342686

### Задача 3
 
В условиях предыдущей задачи сколько выстрелов нужно сделать чтобы быть уверенным с вероятностью 0.9, что хотя бы 10 раз будет совершено попадание?
Подсказка. Как посчитать P(X >= k) для величины X, имеющей распределение Пуассона? Здесь предстоит немножко покодить.

Мы знаем, что сумма вероятностей случайной величины всегда равна $1$. Значит, вероятность получить более 10 попаданий равна:

$$P(X >= 10) = 1 - P(X < 10)$$

Нам нужно быть уверенным с вероятностью 0.9, что хотя бы 10 раз будет совершено попадание, т.е.:

$$P(X >= 10) = 0.9$$ 

Найдем P(X < 10):

$$P(X >= 10) = 0.9$$ 

$$1 - P(X < 10) = 0.9$$

$$P(X < 10) = 1 - 0.9 = 0.1$$



Для решения нужно сложить несколько вероятностей. Вероятность получить менее 10 предполагает получение от 0 до 9 попаданий:
$$P(X < 10) = \displaystyle\sum_{i = 0}^{9} \dfrac{?^{i} e^{-?}}{i!}$$



Значит:

$$\displaystyle\sum_{i = 0}^{9} \dfrac{B^{i} e^{-B}}{i!} = 0.1$$

Найдем b (мат.ожидание):

In [159]:
for b in range(2,20,1):
    c = sum(poisson_proba(k=i, lambda_= b) for i in range(10))
    print(f'при b = {b} c = {round(c,5)}')

при b = 2 c = 0.99995
при b = 3 c = 0.9989
при b = 4 c = 0.99187
при b = 5 c = 0.96817
при b = 6 c = 0.91608
при b = 7 c = 0.8305
при b = 8 c = 0.71662
при b = 9 c = 0.58741
при b = 10 c = 0.45793
при b = 11 c = 0.34051
при b = 12 c = 0.24239
при b = 13 c = 0.16581
при b = 14 c = 0.1094
при b = 15 c = 0.06985
при b = 16 c = 0.0433
при b = 17 c = 0.02612
при b = 18 c = 0.01538
при b = 19 c = 0.00886


Необходимое нам значение с принимает при b (мат.ожидание) = 14

In [160]:
#s (число выстрелов)*0.01 = 14
s = 14/0.01
print(s)

1400.0


In [161]:
print(f'{s} выстрелов нужно сделать \nчтобы быть уверенным с вероятностью 0.9, что хотя бы 10 раз будет совершено попадание')

1400.0 выстрелов нужно сделать 
чтобы быть уверенным с вероятностью 0.9, что хотя бы 10 раз будет совершено попадание
