In [2]:
import numpy as np
import pandas as pd
from scipy import stats
from matplotlib import pyplot as plt
plt.style.use('seaborn-whitegrid')
from itertools import combinations

### Задача 1
 
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). 


In [6]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([ 401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [10]:
X,y

(array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]),
 array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]))

In [11]:
n=len(X)
n

10

Произвести расчет без intercept:

In [13]:
b=(np.mean(X*y)-np.mean(X)*np.mean(y))/(np.mean(X**2)-np.mean(X)**2)
b

2.620538882402765

In [15]:
a=np.mean(y)-b*np.mean(X)
a

444.1773573243596

In [16]:
X=X.reshape((10,1))
y=y.reshape((10,1))

In [17]:
X,y

(array([[ 35],
        [ 45],
        [190],
        [200],
        [ 40],
        [ 70],
        [ 54],
        [150],
        [120],
        [110]]),
 array([[401],
        [574],
        [874],
        [919],
        [459],
        [739],
        [653],
        [902],
        [746],
        [832]]))

In [18]:
B=np.dot(np.linalg.inv(np.dot(X.T,X)),X.T@y)
B

array([[5.88982042]])

Произвести расчет с использованием intercept:

In [19]:
X=np.hstack([np.ones((10,1)), X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [20]:
B=np.dot(np.linalg.inv(np.dot(X.T,X)),X.T@y)
B

array([[444.17735732],
       [  2.62053888]])

### Задача 2
 
Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).


In [ ]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([ 401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [21]:
def mse(B1,y=y,X=X,n=10):
    return np.sum((B1*X-y)**2)/n

In [22]:
B1=0.1

In [23]:
alpha=1e-6
alpha

1e-06

In [25]:
for i in range(10000):
    B1 -= alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%5000==0:
        print(f'i={i}, B1={B1}, mse={mse(B1)}')

i=0, B1=5.940918592497952, mse=582580.1077342933
i=5000, B1=5.940918592497952, mse=582580.1077342933


In [26]:
B1=0.1
B0=0.1

In [27]:
def mse(B0,B1,y=y,X=X,n=10):
    return np.sum((B0+B1*X-y)**2)/n

In [29]:
for i in range(1000000):
    y_pred=B0+B1*X
    B0 -= alpha*(2/n)*np.sum((y_pred-y))
    B1 -= alpha*(2/n)*np.sum((y_pred-y)*X)
    if i%50000==0:
        print(f'i={i}, B1={B1}, mse={mse(B0,B1)}')

i=0, B1=0.417419441544704, mse=1002630.6724996151
i=50000, B1=5.37313621805902, mse=465757.0898866523
i=100000, B1=4.872087867466634, mse=374758.05071556417
i=150000, B1=4.429421396273944, mse=303729.85377009655
i=200000, B1=4.038334179867545, mse=248289.65563966281
i=250000, B1=3.6928162317283766, mse=205016.48102843645
i=300000, B1=3.387557845675099, mse=171240.1291379211
i=350000, B1=3.117867999582535, mse=144876.4071026949
i=400000, B1=2.879602266654389, mse=124298.52344599424
i=450000, B1=2.6690991264350035, mse=108236.70580041439
i=500000, B1=2.483123696826855, mse=95699.84873660261
i=550000, B1=2.3188180224227306, mse=85914.35692573691
i=600000, B1=2.173657155214153, mse=78276.40991133169
i=650000, B1=2.04541035275173, mse=72314.70295551774
i=700000, B1=1.932106797474866, mse=67661.36485826437
i=750000, B1=1.832005310405386, mse=64029.2582136628
i=800000, B1=1.7435675937861697, mse=61194.26140018176
i=850000, B1=1.6654345914724134, mse=58981.43900291467
i=900000, B1=1.5964056037

### Задача 3
В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента? 

### Задача 4
*4. Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).